### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by wmpluto** [Windfarer/ms-shuangpin.cin#2]
我试着把小鹤双拼放到jscin里碰到了和你一样的问题。
不过，小鹤是带辅助形码的，纯打单字了，真难啊

**Comment by Windfarer** [comment]
@wmpluto 我已经放弃了治疗，简直太难搞了。也可能是我们使用的方式不正确

**Comment by wmpluto** [comment]
嗯，暂时没什么好办法了

**Comment by wmpluto** [comment]
你好，趁着假期我这边又折腾了一下。
参考github.com/google/jscin/blob/master/docs/cin.txt
在%chardef begin前添加一行%PHRASE_CHARDEF就可以打出词组了。
翻页的话默认是空格，但是我设置了%SPACE_AUTOUP空格上字，然后就不能翻页了ORZ
另外，我看你有设置%AUTO_COMPOSE，但是我这边好像看不到什么效果。

最后，很感谢你提供的词库，终于是能用了:)

**Comment by Windfarer** [comment]
@wmpluto 感谢，我试试

**Comment by Windfarer** [comment]
刚发现了个这个 https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab?utm_source=chrome-app-launcher-info-dialog
就是用起来有点卡。。

**Comment by wmpluto** [comment]
谢谢，试了一下，功能很全，google的东西很赞。可惜是在线的，卡应该也是这个原因吧。

**Comment by wmpluto** [comment]
已放弃chromeos装ubuntu了
